
mongodb.host=localhost
mongodb.port=27018
mongodb.database=catalog
mongodb.username=master
mongodb.password=pecoso
mongodb.authentication-database=admin

mongodb.maxPoolSize=100
mongodb.minPoolSize=10
mongodb.maxConnectionLifeTime=60000


